//AUTH
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

//NEWS
export const ADD_NEWS = "ADD_NEWS";
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_BY_ID = "GET_NEWS_BY_ID";
export const CLEAR_SELECTED_ITEM = "CLEAR_SELECTED_ITEM";
export const DELETE_NEWS = "DELETE_NEWS";
export const UPDATE_NEWS = "UPDATE_NEWS";

//SCHEDULE
export const GET_SCHEDULE_BY_CATEGORY = "GET_SCHEDULE_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const CREATE_SCHEDULE_ERROR = "CREATE_SCHEDULE_ERROR";
export const CLEAR_CREATE_SCHEDULE_ERROR = "CLEAR_CREATE_SCHEDULE_ERROR";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";

//APPOINTMENTS
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_RESERVED_APPOINTMENTS = "GET_RESERVED_APPOINTMENTS";
export const MAKE_RESERVATION = "MAKE_RESERVATION";
export const CANCEL_RESERVATION = "CANCEL_RESERVATION";
//GALLERY
export const GET_GALLERY = "GET_GALLERY";
export const ADD_IMAGE = "ADD_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";




